export default {
  REGISTER: "REGISTER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  GET_ALL_COMPANIES: "GET_ALL_COMPANIES",
  GET_SINGLE_COMPANY: "GET_SINGLE_COMPANY",
  ADD_COMPANY: "ADD_COMPANY",
  // UPDATE_COMPANY: "UPDATE_COMPANY",
  // DELETE_COMPANY: "DELETE_COMPANY",

  JOIN_COMPANY: "JOIN_COMPANY",
  LEAVE_COMPANY: "LEAVE_COMPANY",

  GET_PROFILE: "GET_PROFILE",

  URL: "http://localhost:8000/api/v1"
};
